source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/zhegu/LZRepos.git'
platform :ios,'13.0'
target 'MMNetworkManagerDemo' do
	pod 'Moya', '14.0.0'
	pod 'Moya/RxSwift', '14.0.0'
	pod 'MMTools'
 	pod 'ObjectMapper'
use_frameworks!
    
end
